services:
  nullsec-website-service:
      build: .
      container_name: nullsec-website-service
      ports:
      - 3000:3000
      volumes:
        - ./website-data/events:/home/website-user/NullSec-Website-2025/website-data/events
      restart: always